import { NextResponse } from "next/server";
import { APP_NAME, APP_DESCRIPTION } from "@/lib/constants";

// Use the verified domain for all manifest URLs
const VERIFIED_URL = "https://baseclaw-v6kt.vercel.app";

export async function GET() {
  const manifest = {
    accountAssociation: {
      header: "eyJmaWQiOjMzNjY0NywidHlwZSI6ImF1dGgiLCJrZXkiOiIweDQzODQ3MzA3OTUwNTNCQzYxNmNiN0FBOTZGNWVBRURhODhjMTQ4N0QifQ",
      payload: "eyJkb21haW4iOiJiYXNlY2xhdy12Nmt0LnZlcmNlbC5hcHAifQ",
      signature: "AAAAAAAAAAAAAAAAyhG94Fl3s2MRZwKIYr4qFzl2yhEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAALgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAkSCrVbLAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAul7REO_bo9AFv8iC11NYrLu4WEIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAVQ_-6NvAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABALHk9BnUmMhpWKXYnbN-EfFIJ2Z27vXrEBT887YPBlQ_9UrmC_7SctV-W4TTf4JzbabGo5npmc60saO9uE_nQqgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAA-FIQshzFAwL0d7pWaG0gGdybZ63hWwqMROytRWUz0BEOrSzgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAKAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAASAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABi9tDRpfVJhOgGa2ownSXyaiQVsBjFwCvowDaexplPC01aHN1cbjHBTU5Dasr7Wk1otwRg4mJuSwuqMNIFoNzFQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAl8ZgIay2xclZzG8RWZzuWvO8j9R0fus3XxDee9lRlVy8dAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACKeyJ0eXBlIjoid2ViYXV0aG4uZ2V0IiwiY2hhbGxlbmdlIjoicExIY2FBX0F0NUtCYTFvdS1iYnpvR3BWQ1J0VzgxcHNNci1HbWQzMEhUYyIsIm9yaWdpbiI6Imh0dHBzOi8va2V5cy5jb2luYmFzZS5jb20iLCJjcm9zc09yaWdpbiI6ZmFsc2V9AAAAAAAAAAAAAAAAAAAAAAAAAAAAAGSSZJJkkmSSZJJkkmSSZJJkkmSSZJJkkmSSZJJkkmSS",
    },
    miniapp: {
      version: "1",
      name: APP_NAME,
      homeUrl: VERIFIED_URL,
      iconUrl: `${VERIFIED_URL}/icon.png`,
      splashImageUrl: `${VERIFIED_URL}/splash.png`,
      splashBackgroundColor: "#111114",
      subtitle: "One-click AI Agent",
      description: APP_DESCRIPTION,
      primaryCategory: "utility",
      tags: ["ai", "agent", "baseclaw", "openclaw", "base"],
      heroImageUrl: `${VERIFIED_URL}/og-image.png`,
      tagline: "Your AI, your keys, your rules",
      ogTitle: APP_NAME,
      ogDescription: APP_DESCRIPTION,
      ogImageUrl: `${VERIFIED_URL}/og-image.png`,
      noindex: false,
    },
  };

  return NextResponse.json(manifest);
}
